### ISSUE TITLE
scripts for switchout family reproduce 

### ISSUE THREAD

**Issue by lizhiustc** [protonish/fairseq-cipherdaug#1]
Hi, really nice work ! I'd like to follow it ! And can you  release your scripts to reprodcue the switchout  results in your paper ?

**Comment by protonish** [comment]
Hi, thanks for your interest in our work.
The scripts are available at https://github.com/protonish/cipherdaug-nmt (the main code repo). Note that this is just a reference implementation.
The exact settings might not be in there but should be straightforward. Closing the issue for now.
